### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getNativeNode' of null

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#256] opened 2016-08-11 20:17 UTC
With a-frame master. Click on `a-collada-model` and then in another entity. Click back on `a-collada-model` and click on the scene view. ![error](https://d3vv6lp55qjaqc.cloudfront.net/items/0C0R033s0o3j1O3B060W/Screen%20Recording%202016-08-11%20at%2001.15.55%20PM.gif?v=bb05ac58)

**Comment by fernandojsg** [comment] 2016-08-12 00:12
@dmarcos it seems to be solved too, can you give it a try?
![selectcollada2](https://cloud.githubusercontent.com/assets/782511/17609109/35295efa-6032-11e6-8f34-d0bed79eba35.gif)

**Comment by fernandojsg** [comment] 2016-08-16 21:27
I'm closing it as I can't reproduce it anymore with the latest changes

**Closed as completed by fernandojsg** 2016-08-16 21:27 UTC
