### ISSUE TITLE
Listen to `componentchanged` event on individual entities rather than on `document`

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#253] opened 2016-08-10 17:31 UTC
I'd like to stop bubbling of the `componentchanged` event as it's better if you're developing and theoretically more performant as components are constantly changing. https://github.com/aframevr/aframe/pull/1758

It was reverted since Inspector relies on bubbling. But we can update it so it doesn't:
- SceneGraph uses it to show the icons. Instead have the Component Panel communicate to the SceneGraph when a component is added.
- `lib/editor.js` uses it to new objects. Can we use `child-attached`?
- `lib/viewport.js` - I would also have the Component Panels emit its own event rather than use the A-Frame event.

**Comment by dmarcos** [comment] 2016-08-10 17:33
We could have a method `on` in the entities to do: `entityEl.on('componentchanged', function() { ... }`
The `on` method will listen only to the entity. We can let the events bubble up when using `addEventListener`

**Comment by ngokevin** [comment] 2016-08-10 17:36
Could. Although, since the intent is to have trigger updates when the component panels are changed, it makes more sense to have the component panels dispatch events. I see this as being more robust that the Inspector only updates when you interact with it rather than rogue JS being able to trigger these.

**Comment by fernandojsg** [comment] 2016-08-10 17:44
I agree that we should make a more clear event path within the components in the inspector.
The problem is how to deal with any change in the DOM, not just directly from the inspector itself. Let's say you modify some DOM on devtools, console, code, should we listen for mutations on the DOM and attach the listener for each entity and its children?

**Comment by ngokevin** [comment] 2016-08-10 17:59
I'm not worried about devtools (which Inspector is supposed to replace) and code (which should be paused). I wouldn't want the Inspector UI automatically fluctuating without user action.

It wouldn't be terrible if we didn't support syncing to changes from console. If a user is changing a component property, they could have just as well used the Inspector. The scene will still update also.

Can we listen to individual entity events in the Component Panel? The only thing that would be hard to update is the icons in the scene graph, which aren't a big deal and only apply when adding/removing components.

**Comment by dmarcos** [comment] 2016-08-10 18:11
We're going to probably have a also a play button within the editor. Also a VR mode where entities will be changed outside of the inspector UI.

**Comment by fernandojsg** [comment] 2016-08-10 18:21
Right now we're using  `MutationObserver` to detect changes on the DOM (Although we're going to remove this in the future https://github.com/aframevr/aframe-inspector/issues/242), so it won't be a problem to detect changes on the scenegraph using that until we'll find a better solution.
I could just listen for `componentchanged` on the selected entity that shows up on the Component Panel.
I also believe it's nice to have in mind a way to detect changes outside the inspector itself for other use cases like the VR-mode that diego commented.

**Comment by ngokevin** [comment] 2016-08-10 18:24
Alright, could listen to `componentchanged` on the selected entity since that's the easiest way now.

Later on, even for VR mode, we'll want an action dispatching system (e.g., Redux) rather than relying on events. This will make every user change a modification to a state machine, which would allow us to do `undo/redo`, and these dispatched actions would propagate through both the VR UI and the Inspector UI. Otherwise, we'd have two UIs separately listening to a single event.

**Comment by fernandojsg** [comment] 2016-08-10 20:04
Just changed it so we don't need to bubble up the event. So you could reapply the issue on aframe  once we merged that PR.

**Comment by ngokevin** [comment] 2016-08-10 20:37
Thanks!

**Closed as completed** 2016-08-10 23:08 UTC
