### ISSUE TITLE
Not obvious that sound component added to scene

### ISSUE THREAD

**Issue by AnnCaryn** [aframevr/aframe-inspector#156] opened 2016-07-08 01:01 UTC
Steps to repro:
Under components tap the dropdown
Add a sound component
Press the plus button
Nothing happens

Expected:
A sound component would likely be added as an additional entity to an object - child attribute?
When a component is added I would expect for it to be highlighted and selected on the left menu.

**Comment by dmarcos** [comment] 2016-07-08 05:10
The component gets added for me but you have to scroll down to see it (components are sorted alphabetically). Two ideas to solve this:
1.  Scroll automatically to the newly added component.
2. Collapse all the components except the created one.

**Comment by cvan** [comment] 2016-07-08 06:43
This seems like a dupe of #140. Can we close in favour of that issue?

**Comment by fernandojsg** [comment] 2016-07-08 09:53
Yes, it's duplicated from #140, let's keep talking there

**Closed as completed by fernandojsg** 2016-07-08 09:53 UTC
