### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#255] opened 2016-08-11 20:04 UTC
With `a-frame` master. Open the anime-ui scene and click on the `a-collada-model` entity. I see the error above.

**Comment by fernandojsg** [comment] 2016-08-12 00:11
@dmarcos can you give it a try on master? I've just tried and it seems to be solved with the latests PRs
![selectcollada1](https://cloud.githubusercontent.com/assets/782511/17609093/0b08f0d6-6032-11e6-88cf-657f2abbc8ea.gif)

**Comment by fernandojsg** [comment] 2016-08-16 21:27
I'm closing it as I can't reproduce it anymore with the latest changes

**Closed as completed by fernandojsg** 2016-08-16 21:27 UTC
